#!/bin/bash
#
# Update static HTML from OpenAPI yaml docs.
#
# see https://dmlls.medium.com/redoc-docs-on-gh-pages-97a8926e9e0f

npx redoc-cli bundle openapi/openapi.yaml

mv redoc-static.html docs/index.html

# add the favicon to 7th row of the file
sed -i '7 i \ \ <link rel="icon" type="image/png" href="favicon.ico"/>' docs/index.html

