#!/bin/bash
#
# Update generated docs using [Snowboard](https://github.com/bukalapak/snowboard):

JSON_DIR="docs/__json__"

git rm $JSON_DIR/*
rm $JSON_DIR/*

docker run -it --rm -v $PWD:/doc quay.io/bukalapak/snowboard html -o docs API.apib

# not sure how to force relative paths with Snowbird, so manually adjust refs
perl -pi -e's|/index.js|index.js|g' docs/index.html
perl -pi -e's|/index.css|index.css|g' docs/index.html

git add -v --all docs/* $JSON_DIR
