openapi: 3.0.3
info:
  title: AUTH Token API
  version: 1.0.0
  description: >-
    This API is documented in **OpenAPI format** and describes how to access AUTH Token data including both public
    data on the blockchain, as well as management API for authenticated vendors and apps.

    WARNING: This API is an early draft and in active development. We are changing things
    rapidly. Once we are ready to release a stable version of this API we will notify app developers on Discord.

    ## General

    * all times are in the UTC timezone

    ## Authentication

    Most APIs are read-only and do not require authentication. Any API used for Reward Code management uses User OAuth token, except for the initial authentication endpoints which are secured by OAuth Client key and secret.

    User OAuth tokens are sent via Authorization Bearer header:


    ```http
       Authorization: Bearer [USER_OAUTH_TOKEN]
    ```
  contact:
    name: AUTH Token API Support
    url: https://discord.com/invite/P842Hxfz
servers:
  - url: "https://{tenant}/api/v1"
    variables:
      tenant:
        default: www
        description: Your tenant id
paths:
  /codes/redeem:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Redeem"

            example:
              code: 8af4ed0f-ee0d-477f-8c5a-d5247528b74e
              wallet: XXXX
              email: me@futurelambo.com

      responses:
        "201":
          description: Created
          headers: {}
          content:
            application/json:
              example:
                redeemed:
                  - code: 8af4ed0f-ee0d-477f-8c5a-d5247528b74e
                    verification: 1f69ec4d-72f8-4d41-bb67-aa67ac476b45
                    wallet: XXXXXX
                  - {}
        "405":
          description: Failed
      summary: Redeem Code
      operationId: redeem_code
      description: >-
        NOTE: This may not be exposed to users, and instead the only redemption
        path is via theauthtoken.com/redeem portal to allow for tighter Vendor
        integration, including redirecting to a vendor specified URL.

        Permanently redeem a Reward Code and associate it with a reward wallet.
        WARNING: This is irreversable. The response includes a list of
        redeemed codes (typically just one) so that multiple code redemption can
        be added in the future. The actual Reward Code is SAFE to return in this
        case since it has been redeemed already.
      tags:
        - codes
      parameters: []

  /codes/{code}:
    get:
      responses:
        "200":
          description: OK
          headers: {}
          content:
            application/json:
              example:
                codes:
                  - verification: 1f69ec4d-72f8-4d41-bb67-aa67ac476b45
                    vendor_slug: ultimatekicks
                    units: 10
                    duration: 52
                    status: redeemed
                    redemption:
                      redeemed_utc: "2022-02-29T04:20:00Z"
                      wallet: XXXXXX
        "400":
          description: Failed
      summary: Code Redemption Status
      operationId: code_statu
      description: >-
        Check if a Reward Code has been redeemed (either with verification code
        or reward code). Prefer using Verification Codes wherever possible to
        avoid potentially leaking a Reward Code in logs/etc that could be then redeemed by an
        unscrupulous middleman. The actual Reward Code is SAFE to return in this
        case since it has been redeemed already. This is a public API, so no private details
        to the vendor associated with the code are exposed.
      tags:
        - codes
      parameters:
        - name: code
          in: path
          description: >-
            check using the Verification Code (or the actual Reward Code) if a
            Reward has been redeemed
          required: true
          schema:
            type: string

  /codes/{code}/detail:
    get:
      responses:
        "200":
          description: OK
        "400":
          description: Invalid Code
      summary: Code Details
      operationId: code_details
      description: >-
        Extended detail on a Reward Code. This is only available when
        authenticated as the Vendor who minted the code originally.
      tags:
        - vendors
      parameters:
        - name: code
          in: path
          description: >-
            check using the Verification Code (or the actual Reward Code) if a
            Reward has been redeemed
          required: true
          schema:
            type: string

  /codes/{code}/extended:
    put:
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid Code
          content:
            application/json:
              example:
                status: 400
                message: "Invalid Code"
      summary: Update Details
      operationId: update_code_details
      description: Update extended detail on a Reward Code. TBD
      tags:
        - vendors
      parameters:
        - name: code
          in: path
          description: >-
            check using the Verification Code (or the actual Reward Code) if a
            Reward has been redeemed
          required: true
          schema:
            type: string

  /codes/mint:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Mint"

      responses:
        "400":
          description: Failed to mint
        "201":
          description: Created
          headers: {}
          content:
            application/json:
              example:
                label: 2022_ST_PATRICK_PROMO
                vendor_slug: ultimatekicks
                units: 10
                duration: 52
                total_codes: 1000
                codes:
                  - code: 8af4ed0f-ee0d-477f-8c5a-d5247528b74e
                    verification: 1f69ec4d-72f8-4d41-bb67-aa67ac476b45
                  - {}
      summary: Mint Reward Codes
      operationId: mint_reward_codes
      description: >-
        Mint new Reward Codes for a Vendor (API request must be authenticated as
        the vendor and the Reward Codes will be assigned to that Vendor).

        NOTE: The cost to the Vendor to mint each Reward Code varies both on the
        Reward Units assigned to each code (per drop) as well as the duration of
        the rewards.
      tags:
        - vendors
      parameters: []

  /purchases/{order_id}:
    get:
      responses:
        "200":
          description: OK
          headers: {}
          content:
            application/json:
              example:
                label: 2022_ST_PATRICK_PROMO
                vendor_slug: ultimatekicks
                units: 10
                duration: 52
                total_codes: 1000
                total_redeemed: 312
        "400":
          description: Failed
      summary: Stats Reward Code Batch
      operationId: reward_code_batch_stats
      description: >-
        Vendor view into the stats for a batch of Reward Codes (number redeemed,
        total, units, duration).
      tags:
        - vendors
      parameters:
        - name: order_id
          in: path
          description: >-
            the purchase_order_id for the batch
          required: true
          schema:
            type: string

    post:
      responses:
        "400":
          description: Failed
        "201":
          description: Created
          headers: {}
          content:
            application/json:
              example: {}
      summary: Manage Reward Code Batch
      operationId: reward_code_batch_manage
      description: >-
        Ability to Manage a batch of Reward Codes by the Vendor. Includes
        assigning various attributes to the batch (after minted). Only the
        original purchasing Vendor of the batch can make modifications.

        + redirectURL (string) - URL that users should be redirected to after
        redeeming a Reward Code (query params will include verification code and
        additional redemption data)

        + label (string) - change the vendor assigned label for this batch of codes
      tags:
        - Codes
      parameters: []

  /vendors:
    get:
      responses:
        "400":
          description: Failed
        "200":
          description: OK
          headers: {}
          content:
            application/json:
              example:
                data:
                  - {}
                cursor: E5Mmsd23aP23xYU0
      summary: Vendors
      operationId: Vendors
      description: >-
        List known vendors that support AUTH as registered on the blockchain and
        statistics on their total Reward Codes (issued, redeemed, etc).

        If a cursor field is present in the response, more results are available.
      tags:
        - vendors
      parameters:
          - name: cursor
            in: query
            description: Returned from an initial query, allowing client to fetch more results
            required: false
            schema:
              type: string
  

    post:
      responses:
        200:
          description: OK
        400:
          description: Failed
      summary: Register Vendor
      operationId: register_vendor
      description: >-
        Register a new Vendor, including the intial Vendor onboarding fee or the annual AUTH burn fee. NOTE: This API is not necessary for now as all Vendors go through an approval process and are manually added to the internal database.
      tags:
        - vendors
      parameters: []

  /vendors/{vendor_slug}:
    get:
      responses:
        "400":
          description: Failed
        "200":
          description: OK
          headers: {}
          content:
            application/json:
              example:
                vendor_id: 909a550a-3573-4c89-93c7-1b258abc966c
                vendor_slug: ultimatekicks
                brand_name: Ultimate Kicks Shoes
                url: https://ultimatekicksforyou.com
                twitter: ultimatekicksforyou
                reward_catalog_url: https://ultimatekicksforyou.com/rewards
                created_utc: "2021-12-25T15:12:55Z"
                status: active
      summary: Vendors
      operationId: vendors
      description: "Data about a given Vendor"
      tags:
        - vendors
      parameters:
        - name: vendor_slug
          in: path
          description: >-
            the slug identifier for the Vendor
          required: true
          schema:
            type: string

  /oracle/prices/current:
    get:
      responses:
        "400":
          description: Failed
        "200":
          description: OK
      summary: Current AUTH Price
      operationId: oracle_price
      description: >-
        Current Oracle Price for AUTH and the block the price took effect.
      tags:
        - oracle
      parameters: []
              
  /oracle/prices:
    get:
      responses:
        "400":
          description: Failed
        "200":
          description: OK
      summary: Historical AUTH Prices
      operationId: historical_oracle_prices
      description: >-
        The current and historical Oracle Prices for AUTH including the block
        that they took effect. Pagination by cursor.
      tags:
        - oracle
      parameters:
        - name: cursor
          in: query
          description: Returned from an initial query, allowing client to fetch more results
          required: false
          schema:
            type: string

  /stats:
    get:
      responses:
        "400":
          description: Failed
        "200":
          description: OK
          headers: {}
          content:
            application/json:
              example:
                token_supply: 124112460.312515
      summary: View Stats
      operationId: stats
      description: ""
      tags:
        - stats
      parameters: []
tags:
  - name: codes
    description: API for interacting with Reward Codes
  - name: vendors
    description: Vendor Management
  - name: oracle
    description: Oracle prices for the AUTH Token
  - name: stats
    description: Blockchain Stats
  - name: code_model
    x-displayName: Reward Code Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Code" />
components:
  schemas:
    Code:
      type: object
      properties:
        verification:
          description: Verification Code (UUIDv4)
          type: string
          minLength: 1
        status:
          type: string
          description: Code Status
          enum:
            - minted
            - redeemed
            - expired

    Mint:
      type: object
      properties:
        label:
          description: >-
            vendor supplied label for this
            batch of Reward Codes (private and only visible to the vendor)
          type: string
          minLength: 1
          maxLength: 100
        total:
          description: number of Reward Codes that should be minted
          type: integer
          minimum: 1
        units:
          description: number of Reward Units for each Reward Code
          type: integer
          minimum: 1
          maximum: 10000
        duration:
          description: number of weeks the Reward Codes will be active for once redeemed
          type: integer
          minimum: 1
          maximum: 260
      required:
        - label
        - total
        - units
        - duration

    Redeem:
      type: object
      properties:
        code:
          description: >-
            Reward Code to redeem
          type: string
          pattern: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
          example: 8af4ed0f-ee0d-477f-8c5a-d5247528b74e
        wallet:
          description: >-
            Solana wallet address this code will be
            redeemed to
          type: string
        email:
          description: >-
            optional email for individual redeeming code
          type: string
          example: me@lambo.com
        vendorSerial:
          description: >-
            optional vendor defined product serial number to associate with this Reward Code
          type: string
      required:
        - code
        - wallet

x-tagGroups:
  - name: General
    tags:
      - codes
      - stats
  - name: Vendor Management
    tags:
      - vendors
  - name: Oracle
    tags:
      - oracle
